apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintMetadata
metadata:
  annotations:
    autogenSpecType: SINGLE_VM
    config.kubernetes.io/local-config: "true"
  name: marketplace-tools
spec:
  content: {}
  info:
    actuationTool:
      flavor: Terraform
      version: '>= 1.2'
    description: {}
    softwareGroups:
    - software:
      - title: Windows Server Datacenter 2019
        version: 10.0.17763
      type: SG_OS
    - software:
      - title: Microsoft SQL Server
        version: "2019"
      - title: SQL Edition
        version: Express
      - title: SQL Version
        version: 15.0.2000.5
      - title: SQL Patch Level
        version: 15.0.4375.4
      - title: Type
        version: RTM-CU27
      - title: SQL Server Management Studio
        version: "20.1"
    title: Google Cloud Marketplace Terraform Module
    version: SQL2019EXP-2024H2
  interfaces:
    outputs:
    - description: Machine type for the compute instance.
      name: instance_machine_type
    - description: External IP of the compute instance.
      name: instance_nat_ip
    - description: Self-link for the network of the compute instance.
      name: instance_network
    - description: Self-link for the compute instance.
      name: instance_self_link
    - description: Zone for the compute instance.
      name: instance_zone
    variables:
    - description: The ID of the project in which to provision resources.
      name: project_id
      required: true
      varType: string
    - description: The name of the deployment and VM instance.
      name: goog_cm_deployment_name
      required: true
      varType: string
    - defaultValue: projects/mpi-gclouds-public/global/images/gclouds-win2019-sql2019-exp-1721319828
      description: The image name for the disk for the VM instance.
      name: source_image
      varType: string
    - defaultValue: us-east1-c
      description: The zone for the solution to be deployed.
      name: zone
      varType: string
    - defaultValue: pd-ssd
      description: The boot disk type for the VM instance.
      name: boot_disk_type
      varType: string
    - defaultValue: 80
      description: The boot disk size for the VM instance in GBs
      name: boot_disk_size
      varType: integer
    - defaultValue: n2d-standard-4
      description: The machine type to create, e.g. e2-small
      name: machine_type
      varType: string
    - defaultValue:
      - default
      description: The network name to attach the VM instance.
      name: networks
      varType: list(string)
    - defaultValue: []
      description: The sub network name to attach the VM instance.
      name: sub_networks
      varType: list(string)
    - defaultValue:
      - EPHEMERAL
      description: The external IPs assigned to the VM for public access.
      name: external_ips
      varType: list(string)
    - defaultValue: true
      description: Allow TCP port 3389 traffic from the Internet
      name: enable_tcp_3389
      varType: bool
    - defaultValue: ""
      description: Source IP ranges for TCP port 3389 traffic
      name: tcp_3389_source_ranges
      varType: string
    - defaultValue: true
      description: Allow TCP port 1433 traffic from the Internet
      name: enable_tcp_1433
      varType: bool
    - defaultValue: ""
      description: Source IP ranges for TCP port 1433 traffic
      name: tcp_1433_source_ranges
      varType: string
    - defaultValue: true
      description: Allow UDP port 1434 traffic from the Internet
      name: enable_udp_1434
      varType: bool
    - defaultValue: ""
      description: Source IP ranges for UDP port 1434 traffic
      name: udp_1434_source_ranges
      varType: string
    - defaultValue: false
      description: Whether to allow sending and receiving of packets with non-matching
        source or destination IPs.
      name: ip_forward
      varType: bool
    - defaultValue: true
      description: Enables Cloud Logging.
      name: enable_cloud_logging
      varType: bool
    - defaultValue: true
      description: Enables Cloud Monitoring.
      name: enable_cloud_monitoring
      varType: bool
